server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EntrePaginasDB
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/